#! /bin/bash

#SBATCH --partition=compute
#SBATCH --job-name=eXpressCounts-longestisoform
#SBATCH --mail-type=ALL
#SBATCH --mail-user=cbecker@whoi.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=150G
#SBATCH --time=02:00:00
#SBATCH --output=eXpress_get_counts_LongestIso-%j.log
#export OMP_NUM_THREADS=1

# USAGE: sbatch eXpress.Longest.sh NameofDeNovoAssembledTXM
# $1 is the name of the de novo assembly

for x in *sorted.bam
do
express $1 $x -o ${x}_LongestTPMfilt_express_output
done

# This script takes each sorted BAM file from SAMtools and maps the reads back to the de novo transcriptome assembly from Trinity (example: Trinity.longest.fasta or Trinity.longest.TPMfilt.fasta)
# The -o flag tells eXpress to put all the files generated by express into the directory express_output.
